hydra:
  run:
    dir: hydra_output/

data:
  data_dir: ./input
  asset_dir: ./assets
  sample_frac: 1.0
  seed: 0
  n_splits: 5

prep:
  kmean_n_cluster: 10
  pca_n_components: 15
  svd_n_components: 15

lgb:
  num_iteration: 6000
  objective: binary
  metric: None
  boosting: dart
  random_state: 42
  is_unbalance: True
  early_stopping_round: 1000
  learning_rate: 0.02
  first_metric_only: True
  num_leaves: 100
  max_depth: -1
  feature_fraction: 0.5
  bagging_fraction: 0.5
  bagging_freq: 10
  lambda_l2: 2
  min_data_in_leaf: 40
  force_col_wise: True

catboost:
  iterations: 500000
  early_stopping_rounds: 1000
  random_state: 42
  use_best_model: True

train:
  exp_name: test
  model_type: lgb
  chunk_size: 5

inference:
  chunk_size: 25

debug: False