hydra:
  run:
    dir: hydra_output/

data:
  data_dir: ./input
  asset_dir: ./assets
  sample_frac: 0.1
  seed: &seed 0
  n_splits: 5

prep:
  kmean_n_cluster: 8
  pca_n_components: 20
  svd_n_components: 20


lgb:
  num_iteration: 100000
  objective: binary
  metric: None
  boosting: gbdt
  random_state: *seed
  early_stopping_round: 100
  learning_rate: 0.01
  first_metric_only: True
  feature_fraction: 0.9
  bagging_fraction: 0.9
  bagging_freq: 1
  verbose: -1

catboost:
  iterations: 500000
  early_stopping_rounds: 1000
  random_state: *seed
  use_best_model: True

train:
  exp_name: test
  model_type: catboost
  chunk_size: 10

inference:
  chunk_size: 25

debug: False