hydra:
  run:
    dir: hydra_output/

data:
  data_dir: ./input
  asset_dir: ./assets
  sample_frac: 0.01
  seed: &seed 0
  n_splits: 5

lgb:
  num_iteration: 100000
  objective: binary
  metric: None
  boosting: gbdt
  random_state: *seed
  early_stopping_round: 100
  learning_rate: 0.01
  first_metric_only: True
  feature_fraction: 0.9
  bagging_fraction: 0.9
  bagging_freq: 1
  verbose: 1


train:
  exp_name: test
